data_source:
  download_url : "https://files.consumerfinance.gov/ccdb/complaints.csv.zip"
  chunk_size : 100000
  target_rows : 200000

data_paths:
  raw_data_dir : "data/bronze"
  raw_data_filename: "complaints_raw.csv.zip"

  silver_data_dir : "data/silver"
  silver_data_filename : "complaints_validated.parquet"

# --- DATA SCHEMA AND TYPES (CRITICAL FOR MEMORY OPTIMIZATION) ---
data_schema:

  usecols_and_dtypes:

    "Date received": "str"
    "Consumer complaint narrative": "str" 
    
    # Categorical Features (using 'category' for memory savings)
    "Product": "category"
    "Sub-product": "category"
    "Issue": "category"
    "Company response to consumer": "category"
    "Timely response?": "category"
    "Consumer disputed?": "category"
    "Company": "category"
    "State": "category"
    "Submitted via": "category"

    "Complaint ID": "int32"