data_source:
  download_url : "https://files.consumerfinance.gov/ccdb/complaints.csv.zip"
  chunk_size : 500000

data_paths:
  raw_data_dir : "data/bronze"
  raw_data_filename: "complaints_raw.csv.zip"

  silver_data_dir : "data/silver"
  silver_data_filename : "complaints_validated.parquet"

# --- DATA SCHEMA AND TYPES (CRITICAL FOR MEMORY OPTIMIZATION) ---
data_schema:
  # Columns to load from the raw file and their required types for memory optimization.
  # Using 'category' for categorical text saves massive amounts of memory.
  usecols_and_dtypes:
    # Core Text/Date
    "Date received": "str" # Keep as string for reading, will convert to datetime later
    "Consumer complaint narrative": "str" # Must be str (will be converted to object later)
    
    # Categorical Features (use 'category' for memory savings)
    "Product": "category"
    "Sub-product": "category"
    "Issue": "category"
    "Company response to consumer": "category"
    "Timely response?": "category"
    "Consumer disputed?": "category"
    "Company": "category"
    "State": "category"
    "Submitted via": "category"
    
    # Identifier (use smallest possible integer type)
    "Complaint ID": "int32"